### ISSUE TITLE
Wider support for start / end

### ISSUE THREAD

**Issue by rufuspollock** [rufuspollock-okfn/wikipediajs#2]
E.g. http://en.wikipedia.org/wiki/Securitas_AB has foundingYear ...

**Comment by Daniel-Mietchen** [comment]
[[CERN]] has dates, headquarters and geolocation, but none of that appears in
http://okfnlabs.org/wikipediajs/?url=http%3A%2F%2Fen.wikipedia.org%2Fwiki%2FCERN .

**Comment by rufuspollock** [comment]
@Daniel-Mietchen excellent point Daniel. BTW when debugging if you click on the "Raw RDF" link at the very bottom of the page you'll see the raw RDF you get from DBPedia. If you can, please let me know what specific attributes I should pull across.

In the case you mention geolocation should be a bug (unless it is not in the raw RDF ...) as I do try to pull all actual geolocation.
