### ISSUE TITLE
Flag absence of infobox

### ISSUE THREAD

**Issue by Daniel-Mietchen** [rufuspollock-okfn/wikipediajs#3]
Articles like [[Philosophy]] that don't have infoboxes cause the tool to stall. A simple message of the "No infobox detected on this page" kind would be better.

**Comment by rufuspollock** [comment]
Hmmm! This info comes via  DBPedia. as Per my comment in #4 suggest clicking on raw RDF or can you see what your debug console says (in FF that would be firebug console ...)

**Comment by rufuspollock** [comment]
@Daniel-Mietchen any thoughts here?

**Comment by rufuspollock** [comment]
INVALID
